services:
  app-prod:
    build: .
    restart: always
    ports:
      - "0.0.0.0:5627:5627"
    volumes:
      - prod_data:/usr/src/app/data
      - .env:/usr/src/app/.env
      - ./config.json:/usr/src/app/config.json
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - REPORT_EMAIL=${REPORT_EMAIL}
      - PROXY_LIST=${PROXY_LIST}
    networks:
      - noog_prod_network

volumes:
  prod_data:
  dev_data:

networks:
  noog_prod_network:
    name: prod_network
  noog_dev_network:
    name: dev_network